ci:
  autoupdate_schedule: "monthly"
  autoupdate_commit_msg: "chore: update pre-commit hooks"
  autofix_prs: false # Comment "pre-commit.ci autofix" on a PR to trigger


default_language_version:
  python: "python3.11"

repos:

  - repo: "https://github.com/pre-commit/pre-commit-hooks"
    rev: "v6.0.0"
    hooks:
      - id: "check-added-large-files"
      - id: "check-case-conflict"
      - id: "check-executables-have-shebangs"
      - id: "check-shebang-scripts-are-executable"
      - id: "check-merge-conflict"
      - id: "check-symlinks"
      - id: "destroyed-symlinks"
      - id: "check-vcs-permalinks"
      - id: "check-json"
      - id: "check-toml"
      - id: "check-yaml"
        # Without --unsafe, !reset in compose YAML triggers error
        args: ["--unsafe"]
      - id: "end-of-file-fixer"
      - id: "mixed-line-ending"
      - id: "trailing-whitespace"

  - repo: "https://github.com/astral-sh/ruff-pre-commit"
    rev: "v0.12.11"
    hooks:
      - id: "ruff"
        # NOTE: "--exit-non-zero-on-fix" is important for CI to function
        # correctly!
        args: ["--fix", "--exit-non-zero-on-fix"]

  - repo: "https://github.com/psf/black"
    rev: "25.1.0"
    hooks:
      - id: "black"

  # Format and validate CFF. NOTE: pre-commit doesn't recognize CFF as YAML
  # (https://github.com/pre-commit/identify/pull/435), so we may need to
  # specify the prettier hook twice if we want to format other things and avoid
  # a messy regex.
  - repo: "https://github.com/rbubley/mirrors-prettier"
    rev: "v3.6.2"
    hooks:
      - id: "prettier"
        files: "CITATION.cff"
  - repo: "https://github.com/citation-file-format/cffconvert"
    rev: "054bda51dbe278b3e86f27c890e3f3ac877d616c"
    hooks:
      - id: "validate-cff"
        args:
          - "--verbose"

  - repo: "https://github.com/codespell-project/codespell"
    rev: "v2.4.1"
    hooks:
      - id: "codespell"
        exclude: ".codespellignore"

  #  TODO: Enable vulture
  # - repo: "https://github.com/jendrikseipp/vulture"
  #   rev: "v2.7"
  #   hooks:
  #     - id: "vulture"

  # TODO: Enable shellcheck
  # # This version requires Docker, which is not available in all CI
  # # providers. Works on GitHub actions but not CircleCI.
  # - repo: "https://github.com/koalaman/shellcheck-precommit"
  #   rev: "v0.9.0"
  #   hooks:
  #     - id: "shellcheck"
  #       # args: ["--severity=warning"]  # Optionally only show errors and warnings
  #
  # # This version does not require Docker
  # - repo: "https://github.com/shellcheck-py/shellcheck-py"
  #   rev: "v0.9.0.5"
  #   hooks:
  #     - id: "shellcheck"
