#!/usr/bin/env bash
# This script is a deployment script tailored to NSIDC's deployment
# environment. It needs to be genericized!
set -euo pipefail

source VERSION.env

# TODO: How to genericize this? These envvars can't go in the Git repository.
# At minimum, we should rename envvars.sh to usaon-vta-survey.sh.
source /etc/profile.d/envvars.sh

# Ensure the production config is present
ln -sf docker-compose.prod.yml docker-compose.override.yml

# We have limited disk space in our deployment environment, so the app needs to
# go down, delete its image, download the new image, and start it back up.
# TODO: Zero-downtime deployments! More compact image!
docker-compose down
docker system prune -af
docker-compose up -d
