"""Add agreement consent tracking to user

Revision ID: 2a175b3a16e1
Revises: 4e1467a2b7a3
Create Date: 2026-07-17 21:35:24.091225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a175b3a16e1'
down_revision: Union[str, None] = '4e1467a2b7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('agreed_agreement_version', sa.String(length=16), nullable=True))
    op.add_column('user', sa.Column('agreed_agreement_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'agreed_agreement_at')
    op.drop_column('user', 'agreed_agreement_version')
    # ### end Alembic commands ###
