"""remove empty assessment_node_subtype_application table.

Revision ID: 3d10329f791c
Revises: 4e1467a2b7a3
Create Date: 2025-08-21 23:10:37.124858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d10329f791c'
down_revision: Union[str, None] = '4e1467a2b7a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assessment_node_subtype_application')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment_node_subtype_application',
    sa.Column('assessment_node_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assessment_node_id'], ['assessment_node.id'], name='fk_assessment_node_subtype_application_assessment_node__082a'),
    sa.PrimaryKeyConstraint('assessment_node_id', name='pk_assessment_node_subtype_application')
    )
    # ### end Alembic commands ###
