"""simplify application fields.

Revision ID: 4e1467a2b7a3
Revises: ce8e6e308e5c
Create Date: 2025-08-21 22:21:09.056783

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4e1467a2b7a3'
down_revision: str | None = 'ce8e6e308e5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assessment_node_subtype_application', 'performance_rating')
    op.drop_column('assessment_node_subtype_application', 'performance_rating_criteria')
    op.drop_column(
        'assessment_node_subtype_application',
        'performance_rating_rationale',
    )
    op.drop_column('assessment_node_subtype_application', 'performance_rating_gaps')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'assessment_node_subtype_application',
        sa.Column(
            'performance_rating_gaps',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'assessment_node_subtype_application',
        sa.Column(
            'performance_rating_rationale',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'assessment_node_subtype_application',
        sa.Column(
            'performance_rating_criteria',
            sa.VARCHAR(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        'assessment_node_subtype_application',
        sa.Column(
            'performance_rating',
            sa.INTEGER(),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
