"""Add new link fields.

Revision ID: 925ed377e31b
Revises: fafa3da67d5e
Create Date: 2024-10-02 16:17:16.949764

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '925ed377e31b'
down_revision: str | None = 'fafa3da67d5e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'link',
        sa.Column(
            'performance_rating_rationale',
            sa.String(length=8192),
            nullable=True,
        ),
    )
    op.add_column(
        'link',
        sa.Column(
            'critically_rating_rationale',
            sa.String(length=8192),
            nullable=True,
        ),
    )
    op.add_column(
        'link',
        sa.Column(
            'gaps_description',
            sa.String(length=8192),
            nullable=True,
        ),
    )
    op.add_column(
        'link',
        sa.Column(
            'attribute_description',
            sa.String(length=512),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('link', 'attribute_description')
    op.drop_column('link', 'gaps_description')
    op.drop_column('link', 'critically_rating_rationale')
    op.drop_column('link', 'performance_rating_rationale')
    # ### end Alembic commands ###
