"""remove prefilled sba reference tables.

Revision ID: ce8e6e308e5c
Revises: d46c4d798847
Create Date: 2024-10-15 23:03:00.302098

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ce8e6e308e5c'
down_revision: str | None = 'd46c4d798847'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('societal_benefit_key_objective')
    op.drop_table('societal_benefit_subarea')
    op.drop_table('societal_benefit_area')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'societal_benefit_area',
        sa.Column('id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint('id', name='pk_societal_benefit_area'),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        'societal_benefit_subarea',
        sa.Column('id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            'societal_benefit_area_id',
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['societal_benefit_area_id'],
            ['societal_benefit_area.id'],
            name='fk_societal_benefit_subarea_societal_benefit_area_id_so_0d93',
        ),
        sa.PrimaryKeyConstraint('id', name='pk_societal_benefit_subarea'),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        'societal_benefit_key_objective',
        sa.Column('id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
        sa.Column(
            'societal_benefit_subarea_id',
            sa.VARCHAR(length=256),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ['societal_benefit_subarea_id'],
            ['societal_benefit_subarea.id'],
            name='fk_societal_benefit_key_objective_societal_benefit_suba_8857',
        ),
        sa.PrimaryKeyConstraint(
            'id',
            'societal_benefit_subarea_id',
            name='pk_societal_benefit_key_objective',
        ),
    )
    # ### end Alembic commands ###
