"""Allow null for link ratings.

Revision ID: ea1181510e10
Revises: 925ed377e31b
Create Date: 2024-10-02 21:27:47.043654

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ea1181510e10'
down_revision: str | None = '925ed377e31b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'link',
        'performance_rating',
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    op.alter_column(
        'link',
        'criticality_rating',
        existing_type=sa.INTEGER(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'link',
        'criticality_rating',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        'link',
        'performance_rating',
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    # ### end Alembic commands ###
