"""Increase length of description columns.

Revision ID: fafa3da67d5e
Revises:
Create Date: 2024-09-27 01:03:09.472099
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'fafa3da67d5e'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'assessment',
        'description',
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=4096),
        existing_nullable=True,
    )
    op.alter_column(
        'node',
        'description',
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=4096),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'node',
        'description',
        existing_type=sa.String(length=4096),
        type_=sa.VARCHAR(length=512),
        existing_nullable=True,
    )
    op.alter_column(
        'assessment',
        'description',
        existing_type=sa.String(length=4096),
        type_=sa.VARCHAR(length=512),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
